#!/bin/bash

if [ $(uname) = "Linux" ]; then
    pathCmd="readlink -f"
elif [ $(uname) = "Darwin" ]; then
    pathCmd="stat -f %N"
else
    pathCmd="realpath"
fi

BASEDIR=`dirname $($pathCmd $0)`
TARGET=`echo $BASEDIR/target/scala-*/ostrich-assembly*.jar`
LIBDIR=$BASEDIR/lib
SCALA=scala
JAVA=java
export JAVA_OPTS="-Xss100m -Xmx2000m"

princessParams=()
ostrichSolver=ostrich.OstrichStringTheory
ostrichParams=""

help() {
    echo "Usage: $0 <options>* <file>*"
    echo " "
    echo " Usual options:"
    echo "  [+-]incremental:         Enable incremental solving                         (default:-)"
    echo "  [+-]model:               Print model                                        (default:-)"
    echo "  -timeout=<val>:          Set timeout to <val> milliseconds                  (default:infy)"
    echo "  [+-]eager:               Eagerly intersect automata                         (default:-)"
    echo "  [+-]minimizeAutomata:    Minimize automata                                  (default:-)"
    echo " "
    echo " String solver options:"
    echo "  [+-]cea:                 Use the cost-enriched automata solver              (default:-)"
    echo "  [+-]seq:                 Use the sequential string solver"
    echo "  -ceaBackend=<backend>:   Use <backend> for cost-enriched automata solver:   (default:unary)"
    echo "                                            (unary, nuxmv, catra)"
    echo "  -nuxmvBackend=<backend>: Use <backend> for cost-enriched automata solver:   (default:ic3)"
    echo "                                            (ic3, bmc)"
    echo " "
    echo " Debugging options:"
    echo "  [+-]debug:               Enable debugging                                   (default:-)"
    echo "  [+-]log:                 Enable logging                                     (default:-)"
    echo "  -h:                      Print this help message"
}

for p; do
    case "$p" in
        [+-]eager | [+-]minimizeAutomata | -ceaBackend=* | -nuxmvBackend=* | [+-]debug | [+-]log)
            if [ x"$ostrichParams" = x"" ]; then
                ostrichParams=$p
            else
                ostrichParams=$ostrichParams,$p
            fi
            ;;
        -h)
            help
            exit 0
            ;;
        -cea)
            ostrichSolver=ostrich.OstrichStringTheory
            ;;
        +cea)
            ostrichSolver=ostrich.cesolver.stringtheory.CEStringTheory
            ;;
        +seq)
            ostrichSolver=ap.theories.strings.SeqStringTheory
            ;;
        *)
            princessParams+=("$p")
            ;;
    esac
done

exec $JAVA $JAVA_OPTS -cp $TARGET \
     ostrich.OstrichMain -stringSolver=$ostrichSolver:$ostrichParams \
     "${princessParams[@]}"
