#!/bin/sh

SOLVER=../sloth

TESTS="simple-cvc-smtlib.smt2 \
       simple-cycle.smt2 simple-cycle2.smt2 \
       nonlinear.smt2 nonlinear-2.smt2 \
       norn-benchmark-9.smt2 \
       norn-benchmark-9b.smt2 \
       norn-benchmark-9c.smt2 \
       norn-benchmark-9d.smt2 \
       norn-benchmark-9e.smt2 \
       norn-benchmark-9f.smt2 \
       norn-benchmark-9g.smt2 \
       norn-benchmark-9h.smt2 \
       norn-benchmark-9i.smt2 \
       norn-benchmark-9j.smt2 \
       norn-benchmark-9k.smt2 \
       simple-concat.smt2 \
       simple-concat-2.smt2 \
       simple-concat-3.smt2 \
       simple-concat-4.smt2 \
       simple-concat-4b.smt2 \
       simple-concat-5.smt2 \
       simple-concat-5b.smt2 \
       concat.smt2 \
       simple-replace.smt2 \
       simple-replace-1b.smt2 \
       simple-replace-1c.smt2 \
       simple-replace-1d.smt2 \
       simple-replace-1e.smt2 \
       simple-replace-1f.smt2 \
       simple-replace-1g.smt2 \
       simple-replace-2.smt2 \
       simple-replace-2b.smt2 \
       simple-replace-2c.smt2 \
       simple-replace-2d.smt2 \
       simple-replace-3.smt2 \
       simple-replace-3b.smt2 \
       simple-replace-4.smt2 \
       simple-replace-4b.smt2 \
       simple-replace-4c.smt2 \
       extract-1.smt2 \
       extract-1b.smt2 \
       empty-concat.smt2 \
       escapeSequences-1a.smt2 \
       escapeSequences-1b.smt2 \
       epsilon-1.smt2 \
       epsilon-2.smt2"

for name in $TESTS; do
    echo
    echo $name
    $SOLVER "$@" $name 2>&1 # | grep -v 'time'
done

